f <- read.table("hpc.txt",header=TRUE,sep=";",colClasses="character")
f$Date <- as.Date(f$Date,"%d/%m/%Y")
elec <- subset(f,f$Date=="2007-02-01" | f$Date=="2007-02-02")
elec$Global_active_power <- as.numeric(elec$Global_active_power)
with(elec,hist(Global_active_power,col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power"))
